# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'admm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nadmm.proto\x12\x04\x61\x64mm\"-\n\x0bLocalUpdate\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\x10\n\x08x_plus_u\x18\x02 \x03(\x01\"B\n\x0f\x43onsensusVector\x12\t\n\x01z\x18\x01 \x03(\x01\x12\x11\n\titeration\x18\x02 \x01(\x05\x12\x11\n\tconverged\x18\x03 \x01(\x08\"g\n\x0fTrainingMetrics\x12\x11\n\titeration\x18\x01 \x01(\x05\x12\x17\n\x0fprimal_residual\x18\x02 \x01(\x01\x12\x15\n\rdual_residual\x18\x03 \x01(\x01\x12\x11\n\tconverged\x18\x04 \x01(\x08\"\x07\n\x05\x45mpty2\x7f\n\x0b\x43oordinator\x12>\n\x12\x41ggregateGradients\x12\x11.admm.LocalUpdate\x1a\x15.admm.ConsensusVector\x12\x30\n\nGetMetrics\x12\x0b.admm.Empty\x1a\x15.admm.TrainingMetricsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOCALUPDATE']._serialized_start=20
  _globals['_LOCALUPDATE']._serialized_end=65
  _globals['_CONSENSUSVECTOR']._serialized_start=67
  _globals['_CONSENSUSVECTOR']._serialized_end=133
  _globals['_TRAININGMETRICS']._serialized_start=135
  _globals['_TRAININGMETRICS']._serialized_end=238
  _globals['_EMPTY']._serialized_start=240
  _globals['_EMPTY']._serialized_end=247
  _globals['_COORDINATOR']._serialized_start=249
  _globals['_COORDINATOR']._serialized_end=376
# @@protoc_insertion_point(module_scope)
